### ISSUE TITLE
适配器bard在配置中消失

### ISSUE THREAD

**Issue by fatinghenji** [dingyi222666/koishi-plugin-chathub#103]
![image](https://github.com/ChatLunaLab/chatluna/assets/37131177/800f652e-c5bb-429b-9eeb-76a1e55d6e8d)
![image](https://github.com/ChatLunaLab/chatluna/assets/37131177/d99f48df-c35b-4ba3-a2fb-9503ab66d403)
![image](https://github.com/ChatLunaLab/chatluna/assets/37131177/230dbba8-8701-4338-af70-ae118699b0ae)
log:
```
2023-11-23 10:09:54 [S] chatluna register plugin plugin-common
2023-11-23 10:09:54 [S] chatluna register plugin bing
2023-11-23 10:09:54 [S] chatluna register plugin spark
2023-11-23 10:09:54 [S] chatluna register plugin search-service
2023-11-23 10:09:54 [S] chatluna register plugin zhipu
2023-11-23 10:09:54 [S] chatluna register plugin bard
2023-11-23 10:09:55 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:55 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:55 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:55 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:55 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:311:19)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:311:19)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ====================ChatLunaError:303====================
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:305:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
2023-11-23 10:09:56 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 303。请联系开发者以解决此问题。
                            at BardRequester._getInitParams (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:311:19)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BardRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\requester.js:189:36)
                            at async BardClient.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\client.js:22:9)
                            at async BardClient.isAvailable (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\client.js:16:17)
                            at async PlatformService.refreshClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:156:29)
                            at async PlatformService.createClient (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:188:9)
                            at async PlatformService.createClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:199:28)
                            at async ChatLunaPlugin.initClients (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:374:13)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-bard-adapter\lib\index.js:25:9
```

**Comment by fatinghenji** [comment]
解决：
cookie过期
