### ISSUE TITLE
长期记忆使用报错

### ISSUE THREAD

**Issue by AILSS521** [dingyi222666/koishi-plugin-chathub#104]
chatluna TypeError: this.pineconeIndex.namespace is not a function
                            at PineconeStore._runPineconeQuery (C:\Users\Administrator\Desktop\kkko\node_modules\langchain\dist\vectorstores\pinecone.cjs:178:46)
                            at PineconeStore.similaritySearchVectorWithScore (C:\Users\Administrator\Desktop\kkko\node_modules\langchain\dist\vectorstores\pinecone.cjs:197:36)
                            at ChatLunaSaveableVectorStore.similaritySearchVectorWithScore (C:\Users\Administrator\Desktop\kkko\node_modules\koishi-plugin-chatluna\lib\llm-core\model\base.js:22:28)
                            at ChatLunaSaveableVectorStore.similaritySearchWithScore (C:\Users\Administrator\Desktop\kkko\node_modules\langchain\dist\vectorstores\base.cjs:112:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ScoreThresholdRetriever.getRelevantDocuments (C:\Users\Administrator\Desktop\kkko\node_modules\langchain\dist\retrievers\score_threshold.cjs:36:29)
                            at async VectorStoreRetrieverMemory.loadMemoryVariables (C:\Users\Administrator\Desktop\kkko\node_modules\langchain\dist\memory\vector_store.cjs:58:25)
                            at async ChatHubChatChain.call (C:\Users\Administrator\Desktop\kkko\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\chat_chain.js:75:29)
                            at async ChatInterfaceWrapper.chat (C:\Users\Administrator\Desktop\kkko\node_modules\koishi-plugin-chatluna\lib\services\chat.js:470:33)
                            at async ChainMiddleware.execute (C:\Users\Administrator\Desktop\kkko\node_modules\koishi-plugin-chatluna\lib\middlewares\request_model.js:49:31)
2023-11-23 10:52:58 [I] loader unload plugin chatluna-vector-store-service:842a0z
2023-11-23 10:52:58 [S] chatluna unregister plugin vector-store-service
2023-11-23 10:52:59 [I] loader apply plugin chatluna-vector-store-service:842a0z
2023-11-23 10:52:59 [S] chatluna register plugin vector-store-service

**Comment by dingyi222666** [comment]
1. 使用长期记忆库需要自己安装相关依赖
2. pinecone 免费版可能不在支持 namespace

**Comment by dingyi222666** [comment]
追加：已移除 pinecone 相关支持，推荐使用 faiss 或 redis (redis 需要安装向量支持，chatluna 将会在新版本支持 redis 作为向量数据库的后端）
