### ISSUE TITLE
[Bug] chatluna 在 koishi 4.17.9+ 版本无法启动

### ISSUE THREAD

**Issue by dezhishen** [dingyi222666/koishi-plugin-chathub#187]
## 版本
- koishi: 4.17.9
- chatluna: 当前版本：1.0.0-beta.52
- chatluna-openai-like-adapter : 1.0.0-beta.8
- database-mysql: 6.4.1
- mysql: maridb-11.3.2
## 错误日志
```
2024-06-18 14:01:24 [I] loader apply plugin chatluna-openai-like-adapter:52smk5
2024-06-18 14:01:24 [E] app TypeError: ctx.runtime.inject.add is not a function
                            at new ChatLunaPlugin (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.js:358:28)
                            at Object.apply (/koishi/node_modules/koishi-plugin-chatluna-openai-like-adapter/lib/index.js:15:20)
                            at apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:890:26)
                            at /koishi/node_modules/@cordisjs/core/lib/index.cjs:819:31
                            at ForkScope.ensure (/koishi/node_modules/@cordisjs/core/lib/index.cjs:693:18)
                            at ForkScope.start (/koishi/node_modules/@cordisjs/core/lib/index.cjs:819:12)
                            at ForkScope.init (/koishi/node_modules/@cordisjs/core/lib/index.cjs:727:12)
                            at new ForkScope (/koishi/node_modules/@cordisjs/core/lib/index.cjs:809:10)
                            at MainScope.fork (/koishi/node_modules/@cordisjs/core/lib/index.cjs:867:12)
                            at Proxy.plugin (/koishi/node_modules/@cordisjs/core/lib/index.cjs:1062:20)
2024-06-18 14:01:24 [S] chatluna unregister plugin openai-like
```
## 补充截图
![image](https://github.com/ChatLunaLab/chatluna/assets/26274059/e6eeab7d-6da9-4098-aed5-97680b762e9a)

![image](https://github.com/ChatLunaLab/chatluna/assets/26274059/67df198e-1552-41de-adb9-3c06636c63f6)

![image](https://github.com/ChatLunaLab/chatluna/assets/26274059/a1738813-c599-4c6f-b7f3-5d37e54c0cf1)

![image](https://github.com/ChatLunaLab/chatluna/assets/26274059/b0cb9ea3-25ac-467f-a2ff-f180c9012d50)

![image](https://github.com/ChatLunaLab/chatluna/assets/26274059/c3bc7eb6-8e56-4948-8d6d-b48658cd2e52)

**Comment by Neptune1990** [comment]
同，数据库用的sqlite，小火箭后一样报错。

**Comment by dingyi222666** [comment]
chatluna 目前未适配 koishi 新版本 (4.17.9)，请等待我们适配。

目前的解决方法：降级到 koishi 4.17.8

**Comment by dingyi222666** [comment]
目前初步诊断到问题所在,可能短期内无法解决,抱歉.

**Comment by dezhishen** [comment]
> 目前初步诊断到问题所在,可能短期内无法解决,抱歉.

哪有计划吗？
或者能拆解下步骤，让社区参与吗？

**Comment by dingyi222666** [comment]
> > 目前初步诊断到问题所在,可能短期内无法解决,抱歉.
> 
> 哪有计划吗？ 或者能拆解下步骤，让社区参与吗？

主要是需要把本项目从 commonjs 迁移到 esm (由于 koishi 上游的变化).
这需要大量的工作,我不知道怎么让社区参与,我自己已经在做迁移了.
