### ISSUE TITLE
[Bug] 无法正确回复

### ISSUE THREAD

**Issue by yu-xinx** [dingyi222666/koishi-plugin-chathub#243]
发送消息就999

![image](https://github.com/user-attachments/assets/e829006d-bcb3-4a73-a06a-a33c7ea8af0c)

以下是报错代码
```
chatluna ====================ChatLunaError:999====================
chatluna TypeError: generation.message._updateId is not a function
                            at /koishi/node_modules/koishi-plugin-chatluna/node_modules/@langchain/core/dist/language_models/chat_models.cjs:195:52
                            at Array.map (<anonymous>)
                            at ChatLunaChatModel._generateUncached (/koishi/node_modules/koishi-plugin-chatluna/node_modules/@langchain/core/dist/language_models/chat_models.cjs:188:39)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChatHubLLMChain._call (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:81:29)
                            at async ChatHubLLMChain.invoke (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:121:22)
                            at async callChatHubChain (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:152:20)
                            at async _ChatHubChatChain.call (/koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:1106:22)
                            at async ChatInterface.chat (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chat/app.cjs:356:24)
                            at async ChatInterfaceWrapper.chat (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:1118:27)
```

下面是配置截图

![image](https://github.com/user-attachments/assets/3cf032b2-5c65-424c-a9f5-0812e6d900a9)

**Comment by dingyi222666** [comment]
告诉我你目前使用的 chatluna 版本，使用的什么适配器以及适配器版本。

**Comment by dingyi222666** [comment]
是否使用的 cohere 适配器?....

**Comment by dingyi222666** [comment]
以及你使用 chatluna 的方式，是否为 koishi desktop 或者其他方式

**Comment by yu-xinx** [comment]
使用的是通义千问，适配器更新到最新版本已无问题
