### ISSUE TITLE
[Bug] 模型调用任意工具报错：Failed to parse tool arguments from chat model response. SyntaxError: Unterminated string in JSON

### ISSUE THREAD

**Issue by DGCK81LNN** [dingyi222666/koishi-plugin-chathub#254]
`koishi-plugin-chatluna@1.0.0-beta.89`
`koishi-plugin-chatluna-openai-adapter@1.0.0-beta.32`
`koishi-plugin-chatluna-plugin-common@1.0.0-beta.32`

模型：gpt-4o-mini

> chatluna chat text 看一下 https://dgck81lnn.github.io/blog/

> 使用 ChatLuna 时出现错误，错误码为 999。请联系开发者以解决此问题。

~~~
2024-09-26 17:00:20 [E] chatluna Error: Failed to parse tool arguments from chat model response. Text: "【此处JSON见下】". SyntaxError: Unterminated string in JSON at position 2
                            at OpenAIToolsAgentOutputParser.parseAIMessage ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1277:15)
                            at OpenAIToolsAgentOutputParser.parseResult ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1243:19)
                            at RunnableLambda.func ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1364:27)
                            at [...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1619:44
                            at MockAsyncLocalStorage.run ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:12:16)
                            at AsyncLocalStorageProvider.runWithConfig ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:48:24)
                            at output ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1617:64)
                            at new Promise (<anonymous>)
                            at RunnableLambda._transform ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1616:30)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-26 17:00:24 [E] chatluna Error: Failed to parse tool arguments from chat model response. Text: "【除id以外完全相同的JSON，略】". SyntaxError: Unterminated string in JSON at position 2
                            at OpenAIToolsAgentOutputParser.parseAIMessage ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1277:15)
                            at OpenAIToolsAgentOutputParser.parseResult ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1243:19)
                            at RunnableLambda.func ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1364:27)
                            at [...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1619:44
                            at MockAsyncLocalStorage.run ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:12:16)
                            at AsyncLocalStorageProvider.runWithConfig ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:48:24)
                            at output ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1617:64)
                            at new Promise (<anonymous>)
                            at RunnableLambda._transform ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1616:30)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-26 17:00:30 [E] chatluna Error: Failed to parse tool arguments from chat model response. Text: "【除id以外完全相同的JSON，略】". SyntaxError: Unterminated string in JSON at position 2
                            at OpenAIToolsAgentOutputParser.parseAIMessage ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1277:15)
                            at OpenAIToolsAgentOutputParser.parseResult ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1243:19)
                            at RunnableLambda.func ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1364:27)
                            at [...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1619:44
                            at MockAsyncLocalStorage.run ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:12:16)
                            at AsyncLocalStorageProvider.runWithConfig ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\singletons\index.cjs:48:24)
                            at output ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1617:64)
                            at new Promise (<anonymous>)
                            at RunnableLambda._transform ([...]\node_modules\koishi-plugin-chatluna\node_modules\@langchain\core\dist\runnables\base.cjs:1616:30)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-26 17:00:30 [E] chatluna ====================ChatLunaError:999====================
2024-09-26 17:00:30 [E] chatluna TypeError: Cannot read properties of undefined (reading 'output')
                            at _ChatLunaPluginChain.call ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:1531:37)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChatInterface.chat ([...]\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.cjs:356:24)
                            at async ChatInterfaceWrapper.chat ([...]\node_modules\koishi-plugin-chatluna\lib\services\chat.cjs:1118:27)
                            at async ChainMiddleware.execute ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:4470:25)
                            at async ChatChain._runMiddleware ([...]\node_modules\koishi-plugin-chatluna\lib\services\chat.cjs:188:18)
                            at async ChatChain.receiveCommand ([...]\node_modules\koishi-plugin-chatluna\lib\services\chat.cjs:159:20)
                            at async _Command.<anonymous> ([...]\node_modules\koishi-plugin-chatluna\lib\index.cjs:544:5)
                            at Array.<anonymous> ([...]\node_modules\@koishijs\core\src\command\command.ts:291:14)
                            at _Command.execute ([...]\node_modules\@koishijs\core\src\command\command.ts:307:22)
~~~

报错中的 JSON：

~~~json
[
  {
    "id": "call_pVFhngJibW6lououLJ8bj7J6",
    "type": "function",
    "function": { "name": "web-browser", "parameters": null, "arguments": "" }
  },
  { "function": { "name": "", "parameters": null, "arguments": "{\"" } },
  { "function": { "name": "", "parameters": null, "arguments": "input" } },
  { "function": { "name": "", "parameters": null, "arguments": "\":\"" } },
  { "function": { "name": "", "parameters": null, "arguments": "open" } },
  { "function": { "name": "", "parameters": null, "arguments": " https" } },
  { "function": { "name": "", "parameters": null, "arguments": "://" } },
  { "function": { "name": "", "parameters": null, "arguments": "dg" } },
  { "function": { "name": "", "parameters": null, "arguments": "ck" } },
  { "function": { "name": "", "parameters": null, "arguments": "81" } },
  { "function": { "name": "", "parameters": null, "arguments": "ln" } },
  { "function": { "name": "", "parameters": null, "arguments": "n" } },
  { "function": { "name": "", "parameters": null, "arguments": ".github" } },
  { "function": { "name": "", "parameters": null, "arguments": ".io" } },
  { "function": { "name": "", "parameters": null, "arguments": "/blog" } },
  { "function": { "name": "", "parameters": null, "arguments": "/" } },
  { "function": { "name": "", "parameters": null, "arguments": "\"}" } }
]
~~~

看起来调用工具的 JSON 参数被切成了许多小块，导致无法正常解析

**Comment by DGCK81LNN** [comment]
似乎为我使用的 OpenAI 代理服务的问题。
