### ISSUE TITLE
[Bug] 使用搜索时错误999

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#279]
使用onebot平台，ollama适配器，搜索模块配置为浏览模式

2024-10-11 05:15:09 [I] original-message-log 今天天气怎么样
2024-10-11 05:15:09 [D] chatluna middleware check_room executed in 11 ms
2024-10-11 05:15:09 [D] chatluna create request id: f18f8844-adab-452e-9a7c-323b17d7764d for [QQ号] in Axw 的模版克隆房间-8100e480-c4a0-4181-97cf-2cb602add107
2024-10-11 05:15:09 [I] chatluna init embeddings for 无
2024-10-11 05:15:09 [W] chatluna Platform 无 is not supported, falling back to fake embeddings
2024-10-11 05:15:10 [D] chatluna-search-service need search: true, new question: What is today's weather like?
// 省略搜索内容
2024-10-11 05:15:12 [E] chatluna ====================ChatLunaError:999====================
2024-10-11 05:15:12 [E] chatluna TypeError: Cannot read properties of undefined (reading 'length')
                            at ChatLunaChatModel.getNumTokens (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/model.cjs:367:36)
                            at ChatHubChatPrompt.tokenCounter (/koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:117:58)
                            at ChatHubChatPrompt.formatMessages (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/prompt.cjs:123:36)
                            at runNextTicks (node:internal/process/task_queues:60:5)
                            at process.processImmediate (node:internal/timers:449:9)
                            at async ChatHubChatPrompt.formatPromptValue (/koishi/node_modules/@langchain/core/dist/prompts/chat.cjs:151:32)
                            at async ChatHubLLMChain._call (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:81:25)
                            at async ChatHubLLMChain.invoke (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:122:22)
                            at async callChatHubChain (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:155:20)
                            at async _ChatLunaBrowsingChain.call (/koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:198:37)

**Comment by dingyi222666** [comment]
已修复。更新新版本 `search-service` 即可。

**Comment by furryaxw** [comment]
> 已修复。更新新版本 `search-service` 即可。

全部插件已是最新版本

**Comment by dingyi222666** [comment]
`search-service` 是 `1.0.0-beta.42` 吗

**Comment by Evander0** [comment]
我使用的镜像没有接受到beta42的更新



| |
钱昱存
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 10:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ChatLunaLab/chatluna] [Bug] 使用搜索时错误999 (Issue #279) |

search-service 是 1.0.0-beta.42 吗

**Comment by furryaxw** [comment]
> `search-service` 是 `1.0.0-beta.42` 吗

我使用的镜像没有接收到beta42

**Comment by furryaxw** [comment]
> `search-service` 是 `1.0.0-beta.42` 吗

我使用的镜像没有接收到beta42

> > `search-service` 是 `1.0.0-beta.42` 吗
> 
> 我使用的镜像没有接收到beta42

更换官方镜像更新beta42后问题解决
