### ISSUE TITLE
[Bug] 流式输出的和 censor 服务一同使用时出现报错

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [dingyi222666/koishi-plugin-chathub#287]
```
执行 censor 时出现错误: Cannot read properties of null (reading 'content')
```

**Comment by dingyi222666** [comment]
请提供详细日志。

**Comment by Hoshino-Yumetsuki** [comment]
> 请提供详细日志。

```
2024-10-21 19:45:08 [D] chatluna middleware request_model executed in 4159 ms
2024-10-21 19:45:08 [E] chatluna chat-chain: censor error TypeError: Cannot read properties of null (reading 'content')
2024-10-21 19:45:08 [E] chatluna TypeError: Cannot read properties of null (reading 'content')
                            at ChainMiddleware.execute (/koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:3323:15)
                            at ChainMiddleware.run (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:563:17)
                            at ChatChain._runMiddleware (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:305:35)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChatChain.receiveMessage (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:244:20)
                            at async /koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:7291:7
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
```
