### ISSUE TITLE
[Bug] TypeError: text.match is not a function

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#294]
chatluna: beta109
search-service: beta47

2024-10-25 01:40:16 [E] chatluna ====================ChatLunaError:999====================
2024-10-25 01:40:16 [E] chatluna TypeError: text.match is not a function
                            at _Tiktoken.encode (/koishi/node_modules/koishi-plugin-chatluna/node_modules/js-tiktoken/dist/lite.cjs:103:33)
                            at ChatLunaChatModel.getNumTokens (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/model.cjs:405:35)
                            at ChatHubChatPrompt.tokenCounter (/koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:126:58)
                            at ChatHubChatPrompt._formatWithoutMessagesPlaceholder (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/prompt.cjs:220:42)
                            at ChatHubChatPrompt.formatMessages (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/prompt.cjs:140:20)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChatHubChatPrompt.formatPromptValue (/koishi/node_modules/@langchain/core/dist/prompts/chat.cjs:154:32)
                            at async ChatHubLLMChain._call (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:209:25)
                            at async ChatHubLLMChain.invoke (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:96:22)
                            at async callChatHubChain (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/chain/base.cjs:242:20)

**Comment by dingyi222666** [comment]
Same as #289
