### ISSUE TITLE
[Bug] 长期记忆兼容性问题

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#295]
2024-10-25 15:50:44 [D] chatluna create request id: 495641ff-e918-40a6-8fc5-668c384e3e62 for {qq} in {qq}的模版克隆房间-c185ab27-d1ad-4528-9f0a-deccbd1c61af
2024-10-25 15:50:44 [I] chatluna init embeddings for openai/text-embedding-3-small
2024-10-25 15:50:44 [W] chatluna Chat mode plugin is not supported by model ollama/furry-8BQ4:latest, falling back to chat mode
2024-10-25 15:50:44 [D] chatluna Long memory id: {qq} => 8ceee3c12884ac33494e8cb955e519a93207c2e7b8241c51962535fe6df6c223
2024-10-25 15:50:44 [E] chatluna ====================ChatLunaError:999====================
2024-10-25 15:50:44 [E] chatluna Error parsing vector similarity query: query vector blob size (0) does not match index's expected size (6144).

**Comment by dingyi222666** [comment]
目前关闭长期记忆可以解决。

**Comment by dingyi222666** [comment]
更新到 chatluna 新版本。做以下操作：

1. 检查选择的向量数据库和 embeddings
2. 运行 `chatluna.memory.clear` 命令，清空长期记忆。

执行了上面的操作，现在应该可以正常的使用长期记忆。

**Comment by dingyi222666** [comment]
你弄一下，没问题了就关 issue。

**Comment by furryaxw** [comment]
> 更新到 chatluna 新版本。做以下操作：
> 
> 1. 检查选择的向量数据库和 embeddings
> 2. 运行 `chatluna.memory.clear` 命令，清空长期记忆。
> 
> 执行了上面的操作，现在应该可以正常的使用长期记忆。

@dingyi222666 更换nomic-embed-text后又开始同样的错误
使用chatluna.memory.clear后可能会出现307错误或者短暂正常
之后会随机出现同样的错误

```
2025-02-09 22:54:12 [D] chatluna create request id: 657c9173-021d-4737-801a-c0d3de9931df for 3312979032 in Axw 的模版克隆房间-c6770e5b-8843-45e9-9730-356588644bc2
2025-02-09 22:54:12 [I] chatluna init embeddings for ollama/nomic-embed-text:latest
2025-02-09 22:54:12 [D] chatluna-long-memory Long memory id: 星茸_长-3312979032 => 83d8d5a3c07f096480f9e958198bad3d034bdcb9d4abaef05147aa9d58cc82b3
2025-02-09 22:54:13 [D] chatluna-vector-store-service Loading redis store from 83d8d5a3c07f096480f9e958198bad3d034bdcb9d4abaef05147aa9d58cc82b3
2025-02-09 22:54:13 [D] chatluna-long-memory Long memory search: [Axw]说: "rua"
2025-02-09 22:54:13 [E] chatluna ====================ChatLunaError:999====================
2025-02-09 22:54:13 [E] chatluna Error parsing vector similarity query: query vector blob size (3072) does not match index's expected size (6144).
```

**Comment by dingyi222666** [comment]
clear 不行吗？这个错误看起来是向量维度不匹配，换其他的向量模型看看。我这边环境不是好跑 ollama。

**Comment by furryaxw** [comment]
> clear 不行吗？这个错误看起来是向量维度不匹配，换其他的向量模型看看。我这边环境不是好跑 ollama。

clear可以缓解，但是可能会随机复发

**Comment by dingyi222666** [comment]
你这个嵌入模型不会是可以自定义维度的吧...换个嵌入模型看看...有空了我在研究这个嵌入模型

**Comment by furryaxw** [comment]
> 你这个嵌入模型不会是可以自定义维度的吧...换个嵌入模型看看...有空了我在研究这个嵌入模型

mxbai-embed-large
![Image](https://github.com/user-attachments/assets/4d6b66ac-0b0a-4afc-ad67-a162f1f30e1f)

**Comment by furryaxw** [comment]
clear之后聊天报错：
```
2025-02-09 23:22:50 [W] app Error: No vectors provided
                            at RedisVectorStore.addVectors (/koishi/node_modules/@langchain/redis/dist/vectorstores.cjs:112:19)
                            at RedisVectorStore.addDocuments (/koishi/node_modules/@langchain/redis/dist/vectorstores.cjs:98:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChatLunaSaveableVectorStore.addDocumentsFunction (/koishi/node_modules/koishi-plugin-chatluna-vector-store-service/lib/index.cjs:756:11)
                            at async /koishi/node_modules/koishi-plugin-chatluna-long-memory/lib/index.cjs:426:7
                            at async Promise.all (index 0)
                            at async Proxy.parallel (/koishi/node_modules/@cordisjs/core/lib/index.cjs:518:5)
```

**Comment by dingyi222666** [comment]
> clear之后聊天报错：
> 
> ```
> 2025-02-09 23:22:50 [W] app Error: No vectors provided
>                             at RedisVectorStore.addVectors (/koishi/node_modules/@langchain/redis/dist/vectorstores.cjs:112:19)
>                             at RedisVectorStore.addDocuments (/koishi/node_modules/@langchain/redis/dist/vectorstores.cjs:98:21)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>                             at async ChatLunaSaveableVectorStore.addDocumentsFunction (/koishi/node_modules/koishi-plugin-chatluna-vector-store-service/lib/index.cjs:756:11)
>                             at async /koishi/node_modules/koishi-plugin-chatluna-long-memory/lib/index.cjs:426:7
>                             at async Promise.all (index 0)
>                             at async Proxy.parallel (/koishi/node_modules/@cordisjs/core/lib/index.cjs:518:5)
> ```

前面的 Long memory extract，是不是空数组，还是别的什么东西

**Comment by furryaxw** [comment]
更换luna-vdb数据库之后似乎问题没有重现
推测应该是redis数据库兼容问题

**Comment by dingyi222666** [comment]
出现 Error parsing vector similarity query: query vector blob size 是因为你之前使用了向量模型 A 来存储记忆，但是后面又换成了向量模型 B。redis 不支持不同维度的向量模型使用。请固定使用一个向量模型不要一直更换。如需更换则需要清除之前存储的全部记忆。
