### ISSUE TITLE
[Bug] 升级到 0.4.x 版本后报错

### ISSUE THREAD

**Issue by yi03** [dingyi222666/koishi-plugin-chathub#30]
我所有的插件都是最新版。升级到0.4.0或0.4.1的时候会报如下的错。我还试了试新开一个实例，除了默认的什么都没有装，只装了0.4.1版chathub插件，也还是一样的错。
```
2023-05-01 23:13:40 [W] market failed to parse @dingyi222666/koishi-plugin-chathub
2023-05-01 23:13:40 [W] market Error: Cannot find module '@initencounter/vits'
                        Require stack:
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\chat.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\plugin-market\lib\node\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\loader\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\koishi\lib\worker\index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
                            at Module._load (node:internal/modules/cjs/loader:841:27)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
                            at require (node:internal/modules/cjs/helpers:103:18)
                            at Object.<anonymous> (C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js:5:1)
                            at Module._compile (node:internal/modules/cjs/loader:1159:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
                            at Module.load (node:internal/modules/cjs/loader:1037:32)
                            at Module._load (node:internal/modules/cjs/loader:878:12)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
2023-05-01 23:13:40 [W] market failed to parse @dingyi222666/koishi-plugin-chathub-newbing-adapter
2023-05-01 23:13:40 [W] market Error: Cannot find module '@initencounter/vits'
                        Require stack:
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\chat.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub-newbing-adapter\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\plugin-market\lib\node\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\loader\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\koishi\lib\worker\index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
                            at Module._load (node:internal/modules/cjs/loader:841:27)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
                            at require (node:internal/modules/cjs/helpers:103:18)
                            at Object.<anonymous> (C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js:5:1)
                            at Module._compile (node:internal/modules/cjs/loader:1159:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
                            at Module.load (node:internal/modules/cjs/loader:1037:32)
                            at Module._load (node:internal/modules/cjs/loader:878:12)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
2023-05-01 23:13:40 [W] market failed to parse @dingyi222666/koishi-plugin-chathub-openai-adapter
2023-05-01 23:13:40 [W] market Error: Cannot find module '@initencounter/vits'
                        Require stack:
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\chat.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\chat.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub-search-service\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\plugin-market\lib\node\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\@koishijs\loader\lib\index.js
                        - C:\Users\45613\koishi-bot\koishi-app10\node_modules\koishi\lib\worker\index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
                            at Module._load (node:internal/modules/cjs/loader:841:27)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
                            at require (node:internal/modules/cjs/helpers:103:18)
                            at Object.<anonymous> (C:\Users\45613\koishi-bot\koishi-app10\node_modules\@dingyi222666\koishi-plugin-chathub\lib\render.js:5:1)
                            at Module._compile (node:internal/modules/cjs/loader:1159:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
                            at Module.load (node:internal/modules/cjs/loader:1037:32)
                            at Module._load (node:internal/modules/cjs/loader:878:12)
                            at Module.require (node:internal/modules/cjs/loader:1061:19)
```

**Comment by dingyi222666** [comment]
这个错误是因为没装initencounter佬提供的vits服务导致的，我目前已在这个commit https://github.com/dingyi222666/koishi-plugin-chathub/commit/a24fe1cdceb17dc1cc24bb6a7f58eb5adc54145a 里修复，但是具体修复还得等我今晚看看能不能肝出来0.5.0版本然后发版。

目前的临时解决方案：安装open-vits
~~真正的解决方案：更新到0.5.0~~

等0.5.0版本发布后我在关闭此issue

**Comment by yi03** [comment]
> 

有可能是我自己的问题，我现在虽然解决了这个问题但是我也不确定原因是什么。
我首先把镜像源删掉了，然后不报这个错了，但是改报`Error: Cannot find module '@koishijs/censor'`的错了。然后我手动装了@koishijs/censor插件，好像好了。中间还有些小插曲，比如忘了在哪一步装了open-vits插件，比如把chathub系列插件都删了重装了一遍，不确定都删了重装这个操作是不是必要的。
很迷，总之有可能是我自己的问题。不过反正现在解决了。

**Comment by dingyi222666** [comment]
> > 
> 
> 有可能是我自己的问题，我现在虽然解决了这个问题但是我也不确定原因是什么。 我首先把镜像源删掉了，然后不报这个错了，但是改报`Error: Cannot find module '@koishijs/censor'`的错了。然后我手动装了@koishijs/censor插件，好像好了。中间还有些小插曲，比如忘了在哪一步装了open-vits插件，比如把chathub系列插件都删了重装了一遍，不确定都删了重装这个操作是不是必要的。 很迷，总之有可能是我自己的问题。不过反正现在解决了。

不，其实更应该是我的问题，因为这插件应该是可选的，我直接import是错误的，应该是import type才对((

**Comment by dingyi222666** [comment]
0.5.0 版本已修复。
