### ISSUE TITLE
[Bug] Chatluna重载时有概率出现加载顺序错误

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#302]
search服务使用ollama中的模型
小概率事件需要手动重启

2024-10-30 10:21:39 [D] chatluna middleware wipe executed in 11046 ms
2024-10-30 10:21:39 [S] chatluna register plugin vector-store-service
2024-10-30 10:21:39 [S] chatluna register plugin ollama
2024-10-30 10:21:39 [S] chatluna register plugin openai
2024-10-30 10:21:39 [S] chatluna register plugin search-service
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_conversation
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_message
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_room
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_room_member
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_room_group_member
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_user
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_auth_user
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_auth_joined_user
2024-10-30 10:21:39 [I] sqlite auto creating table chathub_auth_group
2024-10-30 10:21:40 [E] chatluna ====================ChatLunaError:307====================
2024-10-30 10:21:40 [E] chatluna ChatLunaError: 错误 307
                            at ClientConfigPool.getConfig (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/config.cjs:66:13)
                            at _PlatformService.randomConfig (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/service.cjs:188:53)
                            at _PlatformService.randomClient (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/service.cjs:191:31)
                            at Proxy.createChatModel (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:1111:34)
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:178:40)
                            at createModel (/koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:1946:23)
                            at runNextTicks (node:internal/process/task_queues:60:5)
                            at process.processTimers (node:internal/timers:511:9)
                            at async /koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:1878:51
2024-10-30 10:21:40 [E] app ChatLunaError: 错误 307
                            at ClientConfigPool.getConfig (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/config.cjs:66:13)
                            at _PlatformService.randomConfig (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/service.cjs:188:53)
                            at _PlatformService.randomClient (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/platform/service.cjs:191:31)
                            at Proxy.createChatModel (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:1111:34)
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:178:40)
                            at createModel (/koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:1946:23)
                            at runNextTicks (node:internal/process/task_queues:60:5)
                            at process.processTimers (node:internal/timers:511:9)
                            at async /koishi/node_modules/koishi-plugin-chatluna-search-service/lib/index.cjs:1878:51
2024-10-30 10:21:40 [S] chatluna unregister plugin search-service
2024-10-30 10:21:40 [D] chatluna --------------------

**Comment by dingyi222666** [comment]
需要手动重启是因为你之前聊天错误太多了，API 被 ChatLuna 判定为不可用。

解决方案: 换更稳定的模型接入。

**Comment by dingyi222666** [comment]
你也可以加大重试次数。
