### ISSUE TITLE
[Bug] koishi 4.12.6 无法安装本插件

### ISSUE THREAD

**Issue by Rinlity** [dingyi222666/koishi-plugin-chathub#31]
docker,appimage,zip运行的koishi latest版本均不能正常安装chathub
![Screenshot_20230502_005147_Chrome Dev](https://user-images.githubusercontent.com/98090091/235493921-2cf4a303-3519-48cb-b115-d3c6a1a4a0ec.jpg)
请告诉我解决方法，感谢//

**Comment by dingyi222666** [comment]
有log错误信息吗？

**Comment by Rinlity** [comment]
![Uploading Screenshot_20230501_235904_Chrome Dev.jpg…]()

**Comment by Rinlity** [comment]
![Screenshot_20230501_235904_Chrome Dev](https://user-images.githubusercontent.com/98090091/235551012-448f88be-111c-4abd-9749-774e4794312f.jpg)

**Comment by Rinlity** [comment]
先装chathub0.4.1也是报一样的错，failed parse

**Comment by Rinlity** [comment]
2023-05-02 07:56:40 [W] market failed to parse @dingyi222666/koishi-plugin-chathub
2023-05-02 07:56:40 [W] market Error: Cannot find module '@initencounter/vits'
                        Require stack:
                        - /home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/render.js
                        - /home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js
                        - /home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/index.js
                        - /home/aka/koishi/koishi-app/node_modules/@koishijs/plugin-market/lib/node/index.js
                        - /home/aka/koishi/koishi-app/node_modules/@koishijs/loader/lib/index.js
                        - /home/aka/koishi/koishi-app/node_modules/koishi/lib/worker/index.js
                            at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
                            at Function.Module._load (node:internal/modules/cjs/loader:773:27)
                            at Module.require (node:internal/modules/cjs/loader:1012:19)
                            at require (node:internal/modules/cjs/helpers:93:18)
                            at Object.<anonymous> (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/render.js:5:1)
                            at Module._compile (node:internal/modules/cjs/loader:1108:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                            at Module.load (node:internal/modules/cjs/loader:988:32)
                            at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                            at Module.require (node:internal/modules/cjs/loader:1012:19)

**Comment by Rinlity** [comment]
能够安装的版本是≤0.3.2，0.4.0和0.4.1都装不上

**Comment by dingyi222666** [comment]
0.5.0 版本已修复。

**Comment by Rinlity** [comment]
dingyi222666/chathub/chat TypeError: undici_1.default.fetch is not a function
                            at Object.fetch (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/utils/request.js:81:37)
                            at Api.getCredentials (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:160:70)
                            at Api.init (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:169:24)
                            at Api.request (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:99:20)
                            at PoeClient.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/client.js:31:39)
                            at PoeAdapter.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/index.js:36:48)
                            at DefaultConversation.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/services/chatService.js:236:53)
                            at async Chat.measureTime (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:26:24)
                            at async Chat.chatWithModel (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:143:26)
                            at async /home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:104:24
2023-05-02 11:35:10 [D] @dingyi222666/chathub/chat [chat-limit/error] 凛(3184015596): 你好

**Comment by Rinlity** [comment]
上述是0.5.0的报错，adapter和chathub都是0.5.0

**Comment by dingyi222666** [comment]
> dingyi222666/chathub/chat TypeError: undici_1.default.fetch is not a function at Object.fetch (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/utils/request.js:81:37) at Api.getCredentials (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:160:70) at Api.init (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:169:24) at Api.request (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/api.js:99:20) at PoeClient.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/client.js:31:39) at PoeAdapter.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub-poe-adapter/lib/index.js:36:48) at DefaultConversation.ask (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/services/chatService.js:236:53) at async Chat.measureTime (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:26:24) at async Chat.chatWithModel (/home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:143:26) at async /home/aka/koishi/koishi-app/node_modules/@dingyi222666/koishi-plugin-chathub/lib/chat.js:104:24 2023-05-02 11:35:10 [D] @dingyi222666/chathub/chat [chat-limit/error] 凛(3184015596): 你好

请检查你的node版本，要求大于等于16.8
