### ISSUE TITLE
[Bug] 无法启动插件：Error [ERR_REQUIRE_ESM]: require() of ES Module ... not supported.

### ISSUE THREAD

**Issue by Cysime** [dingyi222666/koishi-plugin-chathub#319]
使用Koishi的Docker镜像运行
```
System:
OS: Linux 6.8 Alpine Linux
CPU: (4) arm64 Neoverse-N1
Binaries:
Node: 20.16.0
Yarn: 4.1.1
Koishi:
Core: 4.18.2
Console: 5.29.3
```

Chatluna版本：1.0.0-rc.0

安装后，无法启用插件：
WEB UI提示：
_插件加载失败，这可能是插件本身的问题所致。请联系插件作者并反馈此问题。_
日志：
```
2024-11-29 13:42:14 [I] console webui is available at http://127.0.0.1:5140
2024-11-29 13:42:14 [I] auth creating admin account
2024-11-29 13:42:36 [W] config failed to load chatluna
2024-11-29 13:42:36 [W] config Error [ERR_REQUIRE_ESM]: require() of ES Module /koishi/node_modules/fetch-socks/index.js from /koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs not supported.
                        Instead change the require of index.js in /koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs to a dynamic import() which is available in all CommonJS modules.
                            at Object.<anonymous> (/koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs:41:26)
2024-11-29 13:42:44 [I] loader apply plugin chatluna:8821tv
2024-11-29 13:42:44 [E] loader Error [ERR_REQUIRE_ESM]: require() of ES Module /koishi/node_modules/fetch-socks/index.js from /koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs not supported.
                        Instead change the require of index.js in /koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs to a dynamic import() which is available in all CommonJS modules.
                            at Object.<anonymous> (/koishi/node_modules/koishi-plugin-chatluna/lib/utils/request.cjs:41:26)

```

**Comment by Marchccc** [comment]
碰到同样问题

**Comment by dingyi222666** [comment]
下周五我会发布 `1.0.0-rc.1` 版本，该版本将会修复此问题。

如果你现在就很想体验修复后的效果，可前往 Koishi 面板的依赖管理，将 ChatLuna 版本降级为 `1.0.0-beta.128`。

![a511e2d10fcc71be17c9cf10d5da5a1d](https://github.com/user-attachments/assets/3cb76b8e-20a8-462f-8d28-bcb68697bf28)
