### ISSUE TITLE
使用google gemini出险bug

### ISSUE THREAD

**Issue by Esmge** [dingyi222666/koishi-plugin-chathub#324]
日志如下
`2024-12-08 21:55:48 [E] chatluna ChatLunaError: 使用 ChatLuna 时出现错误，错误码为 403。请联系开发者以解决此问题。
                            at getTemplateConversationRoom (/koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:3090:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async ChainMiddleware.execute (/koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:5917:28)
                            at async ChatChain._runMiddleware (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:291:18)
                            at async ChatChain.receiveMessage (/koishi/node_modules/koishi-plugin-chatluna/lib/services/chat.cjs:236:20)
                            at async /koishi/node_modules/koishi-plugin-chatluna/lib/index.cjs:7701:30
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)`

**Comment by dingyi222666** [comment]
前往主插件配置，选择模版房间。

参考： https://chatluna.chat/guide/getting-started.html#%E8%AE%BE%E7%BD%AE%E6%A8%A1%E7%89%88%E6%88%BF%E9%97%B4%E9%85%8D%E7%BD%AE
