### ISSUE TITLE
[Bug] 重载 chathub 设置时配置文件全部丢失

### ISSUE THREAD

**Issue by yi03** [dingyi222666/koishi-plugin-chathub#34]
已经遇到三次了，重载chathub的设置时koishi.yml文件的内容变为空，然后再粘贴之前备份的koishi.yml文件，能正常使用，所以只是koishi.yml文件的内容被删了，没有影响其他的东西。
我还没有找到稳定的复现途径，第一次被删时改的什么选项我忘记了，第二次被删时是改的chathub的isLog选项然后重载，第三次被删时是改的chathub的isProxy选项然后重载。
但是我又试了试，重载这两个选项又不删了，还没找到稳定的复现途径。
koishi.yml文件的内容被删时报了这个错，你看能不能根据这个报错发现什么问题。
```
2023-05-02 13:59:21 [I] app reload plugin @dingyi222666/chathub:8dj3l1
2023-05-02 13:59:21 [D] @dingyi222666/chathub [proxy]
2023-05-02 13:59:21 [D] @dingyi222666/chathub/injectService llminjectService started
2023-05-02 13:59:21 [D] @dingyi222666/chathub/chatService chatService started
2023-05-02 13:59:21 [D] @dingyi222666/chathub/chatService register chat adapter poe
2023-05-02 13:59:21 [D] @dingyi222666/chathub/chatService adapter list: poe
2023-05-02 13:59:21 [D] @dingyi222666/chathub-poe-adapter Poe Adapter started
2023-05-02 13:59:21 [W] app TypeError: Cannot read properties of undefined (reading 'dispose')
                            at C:\Users\65161\koishi-bot\koishi-app11\node_modules\@dingyi222666\koishi-plugin-chathub\lib\services\chatService.js:55:46
                            at llmchat (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:228:14)
                            at event <dispose> (C:\Users\65161\koishi-bot\koishi-app11\node_modules\@dingyi222666\koishi-plugin-chathub\lib\services\chatService.js:332:13)
                            at C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:294:7
                            at Array.filter (<anonymous>)
                            at MainScope.reset (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:291:61)
                            at MainScope.reset (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:465:11)
                            at Object.<anonymous> (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:279:12)
                            at Lifecycle.emit (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:100:16)
                            at Context.emit (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:619:31)
2023-05-02 13:59:21 [E] app TypeError: Cannot read properties of undefined (reading 'dispose')
                            at C:\Users\65161\koishi-bot\koishi-app11\node_modules\@dingyi222666\koishi-plugin-chathub\lib\services\chatService.js:55:46
                            at llmchat (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:228:14)
                            at event <dispose> (C:\Users\65161\koishi-bot\koishi-app11\node_modules\@dingyi222666\koishi-plugin-chathub\lib\services\chatService.js:332:13)
                            at C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:294:7
                            at Array.filter (<anonymous>)
                            at MainScope.reset (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:291:61)
                            at MainScope.reset (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:465:11)
                            at Object.<anonymous> (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:279:12)
                            at Lifecycle.emit (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:100:16)
                            at Context.emit (C:\Users\65161\koishi-bot\koishi-app11\node_modules\cordis\lib\index.cjs:619:31)
2023-05-02 13:59:22 [I] app Koishi/4.12.7
2023-05-02 13:59:22 [E] app TypeError: Cannot read properties of undefined (reading 'plugins')
                            at NodeLoader.createApp (C:\Users\65161\koishi-bot\koishi-app11\node_modules\@koishijs\loader\lib\shared.js:261:74)
                            at start (C:\Users\65161\koishi-bot\koishi-app11\node_modules\koishi\lib\worker\index.js:169:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dingyi222666** [comment]
我自己新开一个实例测试，倒是一下就复现了。。。
不过我自己那个测试开发环境基本就复现不了哈哈
