### ISSUE TITLE
[Help] RWKV 适配器无法启用

### ISSUE THREAD

**Issue by Lightupsky** [dingyi222666/koishi-plugin-chathub#46]
TypeError: missing required value
                            at Function.resolve (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:188:13)
                            at property (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:348:37)
                            at C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:408:19
                            at Function.resolve (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:203:12)
                            at C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:431:26
                            at Function.resolve (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:203:12)
                            at schema (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:12:19)
                            at resolveConfig (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:201:14)
                            at _NodeLoader.forkPlugin (C:\Users\light\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\loader\lib\shared.js:221:35)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)

找到了相关的Koishi Issue：https://github.com/koishijs/koishi/issues/1020
佬的开发效率太高啦ヽ(✿ﾟ▽ﾟ)ノ

**Comment by dingyi222666** [comment]
这是不应该的吧。。。你填写对应的参数了吗？

![image.png](https://s2.loli.net/2023/08/01/OrADp36vhgxWjcT.png)

**Comment by dingyi222666** [comment]
上面两个都要填

**Comment by Lightupsky** [comment]
我找到真正的问题了，Apikey默认值是sk-，因为我rwkv后端也没修改过，所以没有修改这个值。检查koishi.yml之后发现这个字段没有写入，随便改了个值保存后就有了，可以正常启用了。

**Comment by dingyi222666** [comment]
> 我找到真正的问题了，Apikey默认值是sk-，因为我rwkv后端也没修改过，所以没有修改这个值。检查koishi.yml之后发现这个字段没有写入，随便改了个值保存后就有了，可以正常启用了。

那我知道是什么问题了，我如果设置了 default 值，那就不应该设置 require 属性（
下个版本会改的
