### ISSUE TITLE
启动插件报错：ReadableStream is not defined

### ISSUE THREAD

**Issue by fatinghenji** [dingyi222666/koishi-plugin-chathub#92]
```
2023-11-17 22:36:07 [I] loader apply plugin chatluna:v7kdly
2023-11-17 22:36:08 [E] loader ReferenceError: ReadableStream is not defined
                            at Object.<anonymous> (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\langchain\dist\util\stream.cjs:8:38)
                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
                            at Module.load (node:internal/modules/cjs/loader:1069:32)
                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
                            at Module.require (node:internal/modules/cjs/loader:1093:19)
                            at require (node:internal/modules/cjs/helpers:108:18)
                            at Object.<anonymous> (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\langchain\dist\callbacks\handlers\log_stream.cjs:6:21)
                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
2023-11-17 22:36:10 [W] config failed to load chatluna
2023-11-17 22:36:10 [W] config ReferenceError: ReadableStream is not defined
                            at Object.<anonymous> (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\langchain\dist\util\stream.cjs:8:38)
                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
                            at Module.load (node:internal/modules/cjs/loader:1069:32)
                            at Function.Module._load (node:internal/modules/cjs/loader:904:12)
                            at Module.require (node:internal/modules/cjs/loader:1093:19)
                            at require (node:internal/modules/cjs/helpers:108:18)
                            at Object.<anonymous> (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\langchain\dist\callbacks\handlers\log_stream.cjs:6:21)
                            at Module._compile (node:internal/modules/cjs/loader:1191:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
```

**Comment by dingyi222666** [comment]
你是否在使用 Koishi Desktop？chatluna 不支持 Node v18 以下的版本。建议使用 Koishi 模版项目方式搭建使用。

**Comment by fatinghenji** [comment]
收到，会尝试该方案以解决问题。
