### ISSUE TITLE
在配置代理后遇到错误：Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by fatinghenji** [dingyi222666/koishi-plugin-chathub#93]
```
2023-11-17 23:32:32 [W] app Error: connect ETIMEDOUT 1.15.53.233:443
                            at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
2023-11-17 23:32:32 [W] app Error: connect ETIMEDOUT 1.15.53.233:443
                            at AxiosError.from (C:\Users\VantHoff\Documents\koishi-app\node_modules\axios\dist\node\axios.cjs:837:14)
                            at RedirectableRequest.handleRequestError (C:\Users\VantHoff\Documents\koishi-app\node_modules\axios\dist\node\axios.cjs:3083:25)
                            at RedirectableRequest.emit (node:events:514:28)
                            at eventHandlers.<computed> (C:\Users\VantHoff\Documents\koishi-app\node_modules\follow-redirects\index.js:14:24)
                            at ClientRequest.emit (node:events:514:28)
                            at TLSSocket.socketErrorListener (node:_http_client:495:9)
                            at TLSSocket.emit (node:events:514:28)
                            at emitErrorNT (node:internal/streams/destroy:151:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-11-17 23:32:32 [W] app Error: connect ETIMEDOUT 1.15.53.233:443
                            at request (C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis-axios\lib\index.js:153:21)
                            at http (C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis-axios\lib\index.js:172:30)
                            at _Quester.get (C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis-axios\lib\index.js:214:16)
                            at C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-open-vits\lib\index.js:22:54
                            at C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis\lib\index.cjs:168:40
                            at _MainScope.ensure (C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis\lib\index.cjs:272:18)
                            at Proxy.start (C:\Users\VantHoff\Documents\koishi-app\node_modules\cordis\lib\index.cjs:168:21)
                            at start (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi\lib\worker\index.js:150:13)
```
代理地址是：`https://127.0.0.1:7890`
目前尝试了在clash中启用tun模式，问题依旧存在。

**Comment by fatinghenji** [comment]
关闭，似乎不影响使用。

**Comment by dingyi222666** [comment]
此错误并未 chatluna 相关错误。
