### ISSUE TITLE
调用报错：305

### ISSUE THREAD

**Issue by fatinghenji** [dingyi222666/koishi-plugin-chathub#94]
发送指令：`chatluna.chat.text`
机器人返回：使用 ChatLuna 时出现错误，错误码为 305。请联系开发者以解决此问题。
控制台输出：
```
2023-11-18 10:30:16 [S] chatluna 已为用户 Alice 自动创建模版克隆房间 Alice 的模版克隆房间。
2023-11-18 10:30:16 [I] chatluna init embeddings for 无
2023-11-18 10:30:16 [W] chatluna Platform 无 is not supported, falling back to fake embeddings
2023-11-18 10:30:16 [E] chatluna ====================ChatLunaError:305====================
2023-11-18 10:30:16 [E] chatluna Error: Vector store retriever 无 not found
                            at PlatformService.createVectorStore (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:134:19)
                            at ChatInterface._initVectorStoreMemory (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:203:41)
                            at ChatInterface.createChatHubLLMChainWrapper (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:69:53)
                            at async ChatInterface.chat (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:25:35)
                            at async ChatInterfaceWrapper.chat (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:470:33)
                            at async ChainMiddleware.execute (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\middlewares\request_model.js:49:31)
                            at async ChatChain._runMiddleware (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\chains\chain.js:110:26)
                            at async ChatChain.receiveCommand (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\chains\chain.js:80:24)
                            at async _Command.<anonymous> (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\commands\chat.js:14:9)
                            at async Array.<anonymous> (C:\Users\VantHoff\Documents\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1331:14)
```

**Comment by TR0MXI** [comment]
2023-11-18 10:30:16 [I] chatluna init embeddings for 无
2023-11-18 10:30:16 [W] chatluna Platform 无 is not supported, falling back to fake embeddings

**Comment by fatinghenji** [comment]
> 2023-11-18 10:30:16 [I] chatluna init embeddings for 无 
2023-11-18 10:30:16 [W] chatluna Platform 无 is not supported, falling back to fake embeddings

是我哪里没有正确配置吗？

**Comment by TR0MXI** [comment]
> > 2023-11-18 10:30:16 [I] chatluna init embeddings for 无 2023-11-18 10:30:16 [W] chatluna Platform 无 is not supported, falling back to fake embeddings
> 
> 是我哪里没有正确配置吗？

配置界面选“无”肯定调用不了的，换其它的模型或者不使用相关功能

**Comment by fatinghenji** [comment]
我切换模型以后出现了类似的报错：
```
2023-11-18 13:05:56 [S] chatluna 已为用户 2909954314 自动切换到公共房间 Bluefissure 的模版克隆房间。
2023-11-18 13:05:56 [I] chatluna init embeddings for 无
2023-11-18 13:05:56 [W] chatluna Platform 无 is not supported, falling back to fake embeddings
2023-11-18 13:05:56 [E] chatluna ====================ChatLunaError:305====================
2023-11-18 13:05:56 [E] chatluna Error: Vector store retriever 无 not found
                            at PlatformService.createVectorStore (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\service.js:134:19)
                            at ChatInterface._initVectorStoreMemory (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:203:41)
                            at ChatInterface.createChatHubLLMChainWrapper (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:69:53)
                            at async ChatInterface.chat (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\chat\app.js:25:35)
                            at async ChatInterfaceWrapper.chat (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\services\chat.js:470:33)
                            at async ChainMiddleware.execute (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\middlewares\request_model.js:49:31)
                            at async ChatChain._runMiddleware (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\chains\chain.js:110:26)
                            at async ChatChain.receiveMessage (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\chains\chain.js:53:24)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\index.js:83:21
                            at async next (C:\Users\VantHoff\Documents\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1053:16)
```
我应该如何正确配置呢？或者应该如何`不使用相关功能`？

**Comment by dingyi222666** [comment]
关闭长期记忆。
