### ISSUE TITLE
调用报错308

### ISSUE THREAD

**Issue by fatinghenji** [dingyi222666/koishi-plugin-chathub#96]
```
2023-11-18 15:50:08 [E] chatluna ====================ChatLunaError:308====================
2023-11-18 15:50:08 [E] chatluna Error: unexpected redirect
                            at makeNetworkError (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\response.js:352:9)
                            at httpFetch (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:1079:18)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:600:16
                            at async mainFetch (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:584:16)
2023-11-18 15:50:08 [E] chatluna TypeError: fetch failed
                            at Object.fetch (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\index.js:110:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async BingRequester._createConversation (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-newbing-adapter\lib\requester.js:391:30)
                            at async BingRequester.init (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-newbing-adapter\lib\requester.js:377:42)
                            at async BingRequester.completionStream (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna-newbing-adapter\lib\requester.js:50:9)
                            at async ChatLunaChatModel._streamResponseChunks (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\model.js:76:26)
                            at async generateWithRetry (C:\Users\VantHoff\Documents\koishi-app\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\model.js:114:34)
                            at async RetryOperation._fn (C:\Users\VantHoff\Documents\koishi-app\node_modules\p-retry\index.js:50:12)
2023-11-18 15:50:08 [E] chatluna Error: unexpected redirect
                            at makeNetworkError (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\response.js:352:9)
                            at httpFetch (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:1079:18)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:600:16
                            at async mainFetch (C:\Users\VantHoff\Documents\koishi-app\node_modules\undici\lib\fetch\index.js:584:16)
```
~怎么感觉我要把所有的错误代码问一遍（~

**Comment by fatinghenji** [comment]
代理问题。
